Repository worm2fed/servant-prometheus, pull requests merged in 2023-12, with the labels that each got.

#7 [chore] Fix ci
  .github/workflows/ci.yml
  bench/Main.hs
  package.yaml
  servant-prometheus.cabal
  stack.yaml
  stack.yaml.lock
  test/Prometheus/ServantSpec.hs
Labels: bug, enhancement

#5 Add an HasEndpoint instance for AuthProtect
  lib/Prometheus/Servant/Internal.hs
Labels: enhancement

#8 [#6]: Update readme
  README.md
Labels: documentation
